# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cat_m.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Categ(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 329)
        self.ca_list = QtWidgets.QListWidget(Dialog)
        self.ca_list.setGeometry(QtCore.QRect(10, 50, 381, 221))
        self.ca_list.setObjectName("ca_list")
        self.sel_c = QtWidgets.QPushButton(Dialog)
        self.sel_c.setGeometry(QtCore.QRect(10, 280, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sel_c.setFont(font)
        self.sel_c.setObjectName("sel_c")
        self.cat_l = QtWidgets.QLabel(Dialog)
        self.cat_l.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cat_l.setFont(font)
        self.cat_l.setAlignment(QtCore.Qt.AlignCenter)
        self.cat_l.setObjectName("cat_l")
        self.new_b = QtWidgets.QPushButton(Dialog)
        self.new_b.setGeometry(QtCore.QRect(220, 280, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.new_b.setFont(font)
        self.new_b.setObjectName("new_b")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sel_c.setText(_translate("Dialog", "Open"))
        self.cat_l.setText(_translate("Dialog", "Select category"))
        self.new_b.setText(_translate("Dialog", "New"))
