# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checking_f.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets
# from main_wnd import Ui_wnd
#
# class Ui_MainMenu(object):
#     def create_b(self):
#         self.openz = QtWidgets.QDialog()
#         self.ui = Ui_wnd()
#         self.ui.setupUi(self.openz)
#         Note_check.close()
#         self.openz.show()
#     def setupUi(self, Dialog):
#         Dialog.setObjectName("Dialog")
#         Dialog.resize(246, 73)
#         self.op_but = QtWidgets.QPushButton(Dialog)
#         self.op_but.setGeometry(QtCore.QRect(10, 30, 93, 28))
#         self.op_but.setObjectName("op_but")
#         self.create_but = QtWidgets.QPushButton(Dialog)
#         self.create_but.setGeometry(QtCore.QRect(140, 30, 93, 28))
#         self.create_but.setObjectName("create_but")
#         self.create_but.clicked.connect(self.create_b)
#
#         self.retranslateUi(Dialog)
#         QtCore.QMetaObject.connectSlotsByName(Dialog)
#
#     def retranslateUi(self, Dialog):
#         _translate = QtCore.QCoreApplication.translate
#         Dialog.setWindowTitle(_translate("Dialog", "Note_check"))
#         self.op_but.setText(_translate("Dialog", "Open"))
#         self.create_but.setText(_translate("Dialog", "Create"))
#
#
# if __name__ == "__main__":
#     import sys
#
#     app = QtWidgets.QApplication(sys.argv)
#     Note_check = QtWidgets.QDialog()
#     ui = Ui_MainMenu()
#     ui.setupUi(Note_check)
#     Note_check.show()
#     sys.exit(app.exec_())