# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_cat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditC(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 206)
        self.next_bt = QtWidgets.QPushButton(Dialog)
        self.next_bt.setGeometry(QtCore.QRect(10, 150, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.next_bt.setFont(font)
        self.next_bt.setObjectName("next_bt")
        self.Editcatn = QtWidgets.QLineEdit(Dialog)
        self.Editcatn.setGeometry(QtCore.QRect(10, 100, 381, 41))
        self.Editcatn.setObjectName("Editcatn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.next_bt.setText(_translate("Dialog", "Next"))
        self.label.setText(_translate("Dialog", "Change category name?"))
