# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_f.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filename(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 142)
        self.got_bt = QtWidgets.QPushButton(Dialog)
        self.got_bt.setGeometry(QtCore.QRect(10, 100, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.got_bt.setFont(font)
        self.got_bt.setObjectName("got_bt")
        self.file_t = QtWidgets.QLineEdit(Dialog)
        self.file_t.setGeometry(QtCore.QRect(10, 50, 381, 41))
        self.file_t.setObjectName("file_t")
        self.enter_l = QtWidgets.QLabel(Dialog)
        self.enter_l.setGeometry(QtCore.QRect(20, 10, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.enter_l.setFont(font)
        self.enter_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enter_l.setAlignment(QtCore.Qt.AlignCenter)
        self.enter_l.setObjectName("enter_l")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.got_bt.setText(_translate("Dialog", "Got it!"))
        self.enter_l.setText(_translate("Dialog", "Enter your filename"))
