# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open_men.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Open(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(567, 393)
        self.listfiles = QtWidgets.QListWidget(Dialog)
        self.listfiles.setGeometry(QtCore.QRect(10, 10, 411, 321))
        self.listfiles.setObjectName("listfiles")
        self.oButton = QtWidgets.QPushButton(Dialog)
        self.oButton.setGeometry(QtCore.QRect(10, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.oButton.setFont(font)
        self.oButton.setObjectName("oButton")
        self.dButton = QtWidgets.QPushButton(Dialog)
        self.dButton.setGeometry(QtCore.QRect(150, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dButton.setFont(font)
        self.dButton.setObjectName("dButton")
        self.cButton = QtWidgets.QPushButton(Dialog)
        self.cButton.setGeometry(QtCore.QRect(290, 340, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.sButton = QtWidgets.QPushButton(Dialog)
        self.sButton.setGeometry(QtCore.QRect(430, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sButton.setFont(font)
        self.sButton.setObjectName("sButton")
        self.rButton = QtWidgets.QPushButton(Dialog)
        self.rButton.setGeometry(QtCore.QRect(430, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rButton.setFont(font)
        self.rButton.setObjectName("rButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.oButton.setText(_translate("Dialog", "Open"))
        self.dButton.setText(_translate("Dialog", "Delete"))
        self.cButton.setText(_translate("Dialog", "Category"))
        self.sButton.setText(_translate("Dialog", "Share"))
        self.rButton.setText(_translate("Dialog", "Return"))
