# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests


class Ui_Sign_up(object):
    # def show_w(self, title, message):
    #     msgBox = QtWidgets.QMessageBox()
    #     msgBox.setIcon(QtWidgets.QMessageBox.Warning)
    #     msgBox.setWindowTitle(title)
    #     msgBox.setText(message)
    #     msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
    #     msgBox.exec_()

    # def confirm_z(self, Sign_up):
    #     username = self.lineEdit.text()
    #     password = self.lineEdit_2.text()
    #     conf_password = self.lineEdit_3.text()
    #     if len(username) == 0:
    #         self.show_w('Warning', 'Empty Username')
    #     if len(password) == 0:
    #         self.show_w('Warning', 'Empty Password')
    #     if password != conf_password:
    #         self.show_w('Warning', 'Different Passwords')
    #     if len(password) > 0 and 0 < len(username) == len(conf_password):
    #         Sign_up.close()
            # param_n = {'username': 'password'}
            # res = requests.post("url", data=param_n)
            # if res:
            #     Sign_up.close()
            # else:
            #     self.show_w('Warning', 'This Username is exist')

    def setupUi(self, Sign_up):
        Sign_up.setObjectName("Sign_up")
        Sign_up.resize(400, 246)
        self.username = QtWidgets.QLabel(Sign_up)
        self.username.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLabel(Sign_up)
        self.password.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.confirm = QtWidgets.QLabel(Sign_up)
        self.confirm.setGeometry(QtCore.QRect(20, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.confirm.setFont(font)
        self.confirm.setObjectName("confirm")
        self.c_password = QtWidgets.QPushButton(Sign_up)
        self.c_password.setGeometry(QtCore.QRect(20, 160, 111, 41))
        # self.c_password.clicked.connect(lambda: self.confirm_z(Sign_up))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.c_password.setFont(font)
        self.c_password.setObjectName("c_password")
        self.lineEdit = QtWidgets.QLineEdit(Sign_up)
        self.lineEdit.setGeometry(QtCore.QRect(170, 20, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Sign_up)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 60, 191, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Sign_up)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 100, 191, 31))
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(Sign_up)
        QtCore.QMetaObject.connectSlotsByName(Sign_up)

    def retranslateUi(self, Sign_up):
        _translate = QtCore.QCoreApplication.translate
        Sign_up.setWindowTitle(_translate("Sign_up", "New User"))
        self.username.setText(_translate("Sign_up", "Username"))
        self.password.setText(_translate("Sign_up", "Password"))
        self.confirm.setText(_translate("Sign_up", "Confirm password"))
        self.c_password.setText(_translate("Sign_up", "Confirm"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Sign_up = QtWidgets.QDialog()
    ui = Ui_Sign_up()
    ui.setupUi(Sign_up)
    Sign_up.show()
    sys.exit(app.exec_())
