# Generated by Django 3.0.7 on 2020-06-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isadded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='my_note',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='notes.Note', verbose_name='Заметки'),
        ),
    ]
