# Generated by Django 3.0.7 on 2020-07-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200630_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='isadded',
        ),
    ]
