# Generated by Django 3.0.7 on 2020-07-02 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_remove_note_isadded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='note_categoria',
            new_name='note_category',
        ),
    ]
