# Generated by Django 3.0.7 on 2020-06-25 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(blank=True, max_length=100, verbose_name='название заметки')),
                ('note_text', models.TextField(verbose_name='заметка')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='дата создания')),
                ('editor', models.ManyToManyField(blank=True, help_text='Вы можете предоставить доступ к вашей заметки', null=True, related_name='editor_note', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_note', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_categoria', models.CharField(max_length=100, unique=True, verbose_name='категория заметки')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_categ', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('my_note', models.ManyToManyField(blank=True, null=True, to='notes.Note', verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
