# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cat_men.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Catm(object):
    def setupUi(self, Categories):
        Categories.setObjectName("Categories")
        Categories.resize(605, 381)
        self.clistWidget = QtWidgets.QListWidget(Categories)
        self.clistWidget.setGeometry(QtCore.QRect(10, 20, 431, 291))
        self.clistWidget.setObjectName("clistWidget")
        self.copushButton = QtWidgets.QPushButton(Categories)
        self.copushButton.setGeometry(QtCore.QRect(10, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.copushButton.setFont(font)
        self.copushButton.setObjectName("copushButton")
        self.cnpushButton = QtWidgets.QPushButton(Categories)
        self.cnpushButton.setGeometry(QtCore.QRect(160, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cnpushButton.setFont(font)
        self.cnpushButton.setObjectName("cnpushButton")
        self.cdpushButton = QtWidgets.QPushButton(Categories)
        self.cdpushButton.setGeometry(QtCore.QRect(310, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cdpushButton.setFont(font)
        self.cdpushButton.setObjectName("cdpushButton")
        self.cmpushButton = QtWidgets.QPushButton(Categories)
        self.cmpushButton.setGeometry(QtCore.QRect(460, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmpushButton.setFont(font)
        self.cmpushButton.setObjectName("cmpushButton")
        self.cepushButton = QtWidgets.QPushButton(Categories)
        self.cepushButton.setGeometry(QtCore.QRect(460, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cepushButton.setFont(font)
        self.cepushButton.setObjectName("cepushButton")

        self.retranslateUi(Categories)
        QtCore.QMetaObject.connectSlotsByName(Categories)

    def retranslateUi(self, Categories):
        _translate = QtCore.QCoreApplication.translate
        Categories.setWindowTitle(_translate("Categories", "Dialog"))
        self.copushButton.setText(_translate("Categories", "Open"))
        self.cnpushButton.setText(_translate("Categories", "New"))
        self.cdpushButton.setText(_translate("Categories", "Delete"))
        self.cmpushButton.setText(_translate("Categories", "Main Menu"))
        self.cepushButton.setText(_translate("Categories", "Edit"))
