# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dshare_u.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dshare(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 430)
        self.duserlabel = QtWidgets.QLabel(Dialog)
        self.duserlabel.setGeometry(QtCore.QRect(20, 20, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.duserlabel.setFont(font)
        self.duserlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.duserlabel.setObjectName("duserlabel")
        self.duserline = QtWidgets.QLineEdit(Dialog)
        self.duserline.setGeometry(QtCore.QRect(20, 60, 381, 41))
        self.duserline.setObjectName("duserline")
        self.user_dbtn = QtWidgets.QPushButton(Dialog)
        self.user_dbtn.setGeometry(QtCore.QRect(20, 390, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.user_dbtn.setFont(font)
        self.user_dbtn.setObjectName("user_dbtn")
        self.dlistWidget = QtWidgets.QListWidget(Dialog)
        self.dlistWidget.setGeometry(QtCore.QRect(20, 120, 381, 251))
        self.dlistWidget.setObjectName("dlistWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.duserlabel.setText(_translate("Dialog", "Enter username"))
        self.user_dbtn.setText(_translate("Dialog", "Got it!"))
