# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_men.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditM(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(485, 76)
        self.mainmen_b = QtWidgets.QPushButton(Dialog)
        self.mainmen_b.setGeometry(QtCore.QRect(10, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mainmen_b.setFont(font)
        self.mainmen_b.setObjectName("mainmen_b")
        self.addNote_b = QtWidgets.QPushButton(Dialog)
        self.addNote_b.setGeometry(QtCore.QRect(170, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addNote_b.setFont(font)
        self.addNote_b.setObjectName("addNote_b")
        self.delNote_b = QtWidgets.QPushButton(Dialog)
        self.delNote_b.setGeometry(QtCore.QRect(330, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delNote_b.setFont(font)
        self.delNote_b.setObjectName("delNote_b")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mainmen_b.setText(_translate("Dialog", "Main Menu"))
        self.addNote_b.setText(_translate("Dialog", "Add Notes"))
        self.delNote_b.setText(_translate("Dialog", "Delete Notes"))
