# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter_u.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(406, 140)
        self.user_btn = QtWidgets.QPushButton(Dialog)
        self.user_btn.setGeometry(QtCore.QRect(10, 100, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.user_btn.setFont(font)
        self.user_btn.setObjectName("user_btn")
        self.userline = QtWidgets.QLineEdit(Dialog)
        self.userline.setGeometry(QtCore.QRect(10, 50, 381, 41))
        self.userline.setObjectName("userline")
        self.userlabel = QtWidgets.QLabel(Dialog)
        self.userlabel.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.userlabel.setFont(font)
        self.userlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.userlabel.setObjectName("userlabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.user_btn.setText(_translate("Dialog", "Got it!"))
        self.userlabel.setText(_translate("Dialog", "Enter username"))
