# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wnd(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.texting = QtWidgets.QTextEdit(Dialog)
        self.texting.setGeometry(QtCore.QRect(0, 0, 401, 251))
        self.texting.setObjectName("texting")
        self.sv_btn = QtWidgets.QPushButton(Dialog)
        self.sv_btn.setGeometry(QtCore.QRect(210, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sv_btn.setFont(font)
        self.sv_btn.setObjectName("sv_btn")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 260, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sv_btn.setText(_translate("Dialog", "Save"))
        self.pushButton.setText(_translate("Dialog", "Return"))
