# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_cat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewC(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 170)
        self.nclabel = QtWidgets.QLabel(Dialog)
        self.nclabel.setGeometry(QtCore.QRect(20, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nclabel.setFont(font)
        self.nclabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nclabel.setObjectName("nclabel")
        self.nclineEdit = QtWidgets.QLineEdit(Dialog)
        self.nclineEdit.setGeometry(QtCore.QRect(10, 60, 341, 41))
        self.nclineEdit.setObjectName("nclineEdit")
        self.ncpushButton = QtWidgets.QPushButton(Dialog)
        self.ncpushButton.setGeometry(QtCore.QRect(10, 110, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ncpushButton.setFont(font)
        self.ncpushButton.setObjectName("ncpushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nclabel.setText(_translate("Dialog", "Enter category"))
        self.ncpushButton.setText(_translate("Dialog", "Got it!"))
